### ISSUE TITLE
Helping Pull request acsept.

### ISSUE THREAD

**Issue by mshalmanov** [ApacheFriends/web-static#24]
Hello.

I new translater in the your project.
I'm add translate file in the project and create new pull request. (https://github.com/ApacheFriends/web-static/pull/23)
Please help me. How i can add reviewers or who can acsept my pull request ? It my first pull request in this project.
I will be werry happy if your helphing me and showing how it made.
Thank you!

**Comment by mshalmanov** [comment]
@ @beltran-rubo @JDLH @gongomgra @grooverdan

**Comment by JDLH** [comment]
@mshalmanov I am happy that you are contributing. Unfortunately, I am just another pull request contributor like you. I have no role with the project. Hopefully one of the others you mentioned can look at your pull request. Good luck!

**Comment by grooverdan** [comment]
me too.

**Comment by beltran-rubo** [comment]
Done, thanks
